# Generated by Django 5.2.4 on 2025-07-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
